/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * OpenAPI spec version: 5.10.0
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CoverEdit } from '../models';
import { CoverList } from '../models';
import { CoverResponse } from '../models';
import { ErrorResponse } from '../models';
import { ReferenceExpansionCoverArt } from '../models';
import { Response } from '../models';
/**
 * CoverApi - axios parameter creator
 * @export
 */
export const CoverApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCover: async (mangaOrCoverId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mangaOrCoverId' is not null or undefined
            if (mangaOrCoverId === null || mangaOrCoverId === undefined) {
                throw new RequiredError('mangaOrCoverId','Required parameter mangaOrCoverId was null or undefined when calling deleteCover.');
            }
            const localVarPath = `/cover/{mangaOrCoverId}`
                .replace(`{${"mangaOrCoverId"}}`, encodeURIComponent(String(mangaOrCoverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {CoverEdit} [body] The size of the body is limited to 2KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editCover: async (contentType: string, mangaOrCoverId: string, body?: CoverEdit, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling editCover.');
            }
            // verify required parameter 'mangaOrCoverId' is not null or undefined
            if (mangaOrCoverId === null || mangaOrCoverId === undefined) {
                throw new RequiredError('mangaOrCoverId','Required parameter mangaOrCoverId was null or undefined when calling editCover.');
            }
            const localVarPath = `/cover/{mangaOrCoverId}`
                .replace(`{${"mangaOrCoverId"}}`, encodeURIComponent(String(mangaOrCoverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary CoverArt list
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {Array<string>} [manga] Manga ids (limited to 100 per request)
         * @param {Array<string>} [ids] Covers ids (limited to 100 per request)
         * @param {Array<string>} [uploaders] User ids (limited to 100 per request)
         * @param {Array<string>} [locales] Locales of cover art (limited to 100 per request)
         * @param {string} [orderCreatedAt] 
         * @param {string} [orderUpdatedAt] 
         * @param {string} [orderVolume] 
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCover: async (limit?: number, offset?: number, manga?: Array<string>, ids?: Array<string>, uploaders?: Array<string>, locales?: Array<string>, orderCreatedAt?: string, orderUpdatedAt?: string, orderVolume?: string, includes?: ReferenceExpansionCoverArt, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cover`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (manga) {
                localVarQueryParameter['manga[]'] = manga;
            }

            if (ids) {
                localVarQueryParameter['ids[]'] = ids;
            }

            if (uploaders) {
                localVarQueryParameter['uploaders[]'] = uploaders;
            }

            if (locales) {
                localVarQueryParameter['locales[]'] = locales;
            }

            if (orderCreatedAt !== undefined) {
                localVarQueryParameter['order[createdAt]'] = orderCreatedAt;
            }

            if (orderUpdatedAt !== undefined) {
                localVarQueryParameter['order[updatedAt]'] = orderUpdatedAt;
            }

            if (orderVolume !== undefined) {
                localVarQueryParameter['order[volume]'] = orderVolume;
            }

            if (includes !== undefined) {
                localVarQueryParameter['includes[]'] = includes;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoverId: async (mangaOrCoverId: string, includes?: ReferenceExpansionCoverArt, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mangaOrCoverId' is not null or undefined
            if (mangaOrCoverId === null || mangaOrCoverId === undefined) {
                throw new RequiredError('mangaOrCoverId','Required parameter mangaOrCoverId was null or undefined when calling getCoverId.');
            }
            const localVarPath = `/cover/{mangaOrCoverId}`
                .replace(`{${"mangaOrCoverId"}}`, encodeURIComponent(String(mangaOrCoverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includes !== undefined) {
                localVarQueryParameter['includes[]'] = includes;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {Blob} [file] 
         * @param {string} [volume] 
         * @param {string} [description] 
         * @param {string} [locale] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadCoverForm: async (contentType: string, mangaOrCoverId: string, file?: Blob, volume?: string, description?: string, locale?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling uploadCoverForm.');
            }
            // verify required parameter 'mangaOrCoverId' is not null or undefined
            if (mangaOrCoverId === null || mangaOrCoverId === undefined) {
                throw new RequiredError('mangaOrCoverId','Required parameter mangaOrCoverId was null or undefined when calling uploadCoverForm.');
            }
            const localVarPath = `/cover/{mangaOrCoverId}`
                .replace(`{${"mangaOrCoverId"}}`, encodeURIComponent(String(mangaOrCoverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (volume !== undefined) { 
                localVarFormParams.append('volume', volume as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            if (locale !== undefined) { 
                localVarFormParams.append('locale', locale as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoverApi - functional programming interface
 * @export
 */
export const CoverApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCover(mangaOrCoverId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await CoverApiAxiosParamCreator(configuration).deleteCover(mangaOrCoverId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Edit Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {CoverEdit} [body] The size of the body is limited to 2KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editCover(contentType: string, mangaOrCoverId: string, body?: CoverEdit, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CoverResponse>>> {
            const localVarAxiosArgs = await CoverApiAxiosParamCreator(configuration).editCover(contentType, mangaOrCoverId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary CoverArt list
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {Array<string>} [manga] Manga ids (limited to 100 per request)
         * @param {Array<string>} [ids] Covers ids (limited to 100 per request)
         * @param {Array<string>} [uploaders] User ids (limited to 100 per request)
         * @param {Array<string>} [locales] Locales of cover art (limited to 100 per request)
         * @param {string} [orderCreatedAt] 
         * @param {string} [orderUpdatedAt] 
         * @param {string} [orderVolume] 
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCover(limit?: number, offset?: number, manga?: Array<string>, ids?: Array<string>, uploaders?: Array<string>, locales?: Array<string>, orderCreatedAt?: string, orderUpdatedAt?: string, orderVolume?: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CoverList>>> {
            const localVarAxiosArgs = await CoverApiAxiosParamCreator(configuration).getCover(limit, offset, manga, ids, uploaders, locales, orderCreatedAt, orderUpdatedAt, orderVolume, includes, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoverId(mangaOrCoverId: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CoverResponse>>> {
            const localVarAxiosArgs = await CoverApiAxiosParamCreator(configuration).getCoverId(mangaOrCoverId, includes, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Upload Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {Blob} [file] 
         * @param {string} [volume] 
         * @param {string} [description] 
         * @param {string} [locale] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadCoverForm(contentType: string, mangaOrCoverId: string, file?: Blob, volume?: string, description?: string, locale?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CoverResponse>>> {
            const localVarAxiosArgs = await CoverApiAxiosParamCreator(configuration).uploadCoverForm(contentType, mangaOrCoverId, file, volume, description, locale, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CoverApi - factory interface
 * @export
 */
export const CoverApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Delete Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCover(mangaOrCoverId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return CoverApiFp(configuration).deleteCover(mangaOrCoverId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {CoverEdit} [body] The size of the body is limited to 2KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editCover(contentType: string, mangaOrCoverId: string, body?: CoverEdit, options?: AxiosRequestConfig): Promise<AxiosResponse<CoverResponse>> {
            return CoverApiFp(configuration).editCover(contentType, mangaOrCoverId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary CoverArt list
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {Array<string>} [manga] Manga ids (limited to 100 per request)
         * @param {Array<string>} [ids] Covers ids (limited to 100 per request)
         * @param {Array<string>} [uploaders] User ids (limited to 100 per request)
         * @param {Array<string>} [locales] Locales of cover art (limited to 100 per request)
         * @param {string} [orderCreatedAt] 
         * @param {string} [orderUpdatedAt] 
         * @param {string} [orderVolume] 
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCover(limit?: number, offset?: number, manga?: Array<string>, ids?: Array<string>, uploaders?: Array<string>, locales?: Array<string>, orderCreatedAt?: string, orderUpdatedAt?: string, orderVolume?: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig): Promise<AxiosResponse<CoverList>> {
            return CoverApiFp(configuration).getCover(limit, offset, manga, ids, uploaders, locales, orderCreatedAt, orderUpdatedAt, orderVolume, includes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Cover
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {ReferenceExpansionCoverArt} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoverId(mangaOrCoverId: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig): Promise<AxiosResponse<CoverResponse>> {
            return CoverApiFp(configuration).getCoverId(mangaOrCoverId, includes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload Cover
         * @param {string} contentType 
         * @param {string} mangaOrCoverId Is Manga UUID on POST
         * @param {Blob} [file] 
         * @param {string} [volume] 
         * @param {string} [description] 
         * @param {string} [locale] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadCoverForm(contentType: string, mangaOrCoverId: string, file?: Blob, volume?: string, description?: string, locale?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CoverResponse>> {
            return CoverApiFp(configuration).uploadCoverForm(contentType, mangaOrCoverId, file, volume, description, locale, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoverApi - object-oriented interface
 * @export
 * @class CoverApi
 * @extends {BaseAPI}
 */
export class CoverApi extends BaseAPI {
    /**
     * 
     * @summary Delete Cover
     * @param {string} mangaOrCoverId Is Manga UUID on POST
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverApi
     */
    public async deleteCover(mangaOrCoverId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return CoverApiFp(this.configuration).deleteCover(mangaOrCoverId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Edit Cover
     * @param {string} contentType 
     * @param {string} mangaOrCoverId Is Manga UUID on POST
     * @param {CoverEdit} [body] The size of the body is limited to 2KB.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverApi
     */
    public async editCover(contentType: string, mangaOrCoverId: string, body?: CoverEdit, options?: AxiosRequestConfig) : Promise<AxiosResponse<CoverResponse>> {
        return CoverApiFp(this.configuration).editCover(contentType, mangaOrCoverId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary CoverArt list
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {Array<string>} [manga] Manga ids (limited to 100 per request)
     * @param {Array<string>} [ids] Covers ids (limited to 100 per request)
     * @param {Array<string>} [uploaders] User ids (limited to 100 per request)
     * @param {Array<string>} [locales] Locales of cover art (limited to 100 per request)
     * @param {string} [orderCreatedAt] 
     * @param {string} [orderUpdatedAt] 
     * @param {string} [orderVolume] 
     * @param {ReferenceExpansionCoverArt} [includes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverApi
     */
    public async getCover(limit?: number, offset?: number, manga?: Array<string>, ids?: Array<string>, uploaders?: Array<string>, locales?: Array<string>, orderCreatedAt?: string, orderUpdatedAt?: string, orderVolume?: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig) : Promise<AxiosResponse<CoverList>> {
        return CoverApiFp(this.configuration).getCover(limit, offset, manga, ids, uploaders, locales, orderCreatedAt, orderUpdatedAt, orderVolume, includes, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Cover
     * @param {string} mangaOrCoverId Is Manga UUID on POST
     * @param {ReferenceExpansionCoverArt} [includes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverApi
     */
    public async getCoverId(mangaOrCoverId: string, includes?: ReferenceExpansionCoverArt, options?: AxiosRequestConfig) : Promise<AxiosResponse<CoverResponse>> {
        return CoverApiFp(this.configuration).getCoverId(mangaOrCoverId, includes, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Upload Cover
     * @param {string} contentType 
     * @param {string} mangaOrCoverId Is Manga UUID on POST
     * @param {Blob} [file] 
     * @param {string} [volume] 
     * @param {string} [description] 
     * @param {string} [locale] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverApi
     */
    public async uploadCoverForm(contentType: string, mangaOrCoverId: string, file?: Blob, volume?: string, description?: string, locale?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CoverResponse>> {
        return CoverApiFp(this.configuration).uploadCoverForm(contentType, mangaOrCoverId, file, volume, description, locale, options).then((request) => request(this.axios, this.basePath));
    }
}
