/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * OpenAPI spec version: 5.10.0
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { ForumsThreadBody } from '../models';
import { ForumsThreadResponse } from '../models';
/**
 * ForumsApi - axios parameter creator
 * @export
 */
export const ForumsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a thread in the forums for the given resource, which backs the comments functionality. A thread is only created if it doesn't exist yet; otherwise the preexisting thread is returned. 
         * @summary Create forums thread
         * @param {ForumsThreadBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forumsThreadCreate: async (body?: ForumsThreadBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/forums/thread`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ForumsApi - functional programming interface
 * @export
 */
export const ForumsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a thread in the forums for the given resource, which backs the comments functionality. A thread is only created if it doesn't exist yet; otherwise the preexisting thread is returned. 
         * @summary Create forums thread
         * @param {ForumsThreadBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forumsThreadCreate(body?: ForumsThreadBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ForumsThreadResponse>>> {
            const localVarAxiosArgs = await ForumsApiAxiosParamCreator(configuration).forumsThreadCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ForumsApi - factory interface
 * @export
 */
export const ForumsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a thread in the forums for the given resource, which backs the comments functionality. A thread is only created if it doesn't exist yet; otherwise the preexisting thread is returned. 
         * @summary Create forums thread
         * @param {ForumsThreadBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forumsThreadCreate(body?: ForumsThreadBody, options?: AxiosRequestConfig): Promise<AxiosResponse<ForumsThreadResponse>> {
            return ForumsApiFp(configuration).forumsThreadCreate(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ForumsApi - object-oriented interface
 * @export
 * @class ForumsApi
 * @extends {BaseAPI}
 */
export class ForumsApi extends BaseAPI {
    /**
     * Creates a thread in the forums for the given resource, which backs the comments functionality. A thread is only created if it doesn't exist yet; otherwise the preexisting thread is returned. 
     * @summary Create forums thread
     * @param {ForumsThreadBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ForumsApi
     */
    public async forumsThreadCreate(body?: ForumsThreadBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<ForumsThreadResponse>> {
        return ForumsApiFp(this.configuration).forumsThreadCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
}
