/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * OpenAPI spec version: 5.10.0
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { InlineResponse20013 } from '../models';
import { RatingMangaIdBody } from '../models';
import { Response } from '../models';
/**
 * RatingApi - axios parameter creator
 * @export
 */
export const RatingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Manga rating
         * @param {string} mangaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRatingMangaId: async (mangaId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mangaId' is not null or undefined
            if (mangaId === null || mangaId === undefined) {
                throw new RequiredError('mangaId','Required parameter mangaId was null or undefined when calling deleteRatingMangaId.');
            }
            const localVarPath = `/rating/{mangaId}`
                .replace(`{${"mangaId"}}`, encodeURIComponent(String(mangaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get your ratings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRating: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/rating`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create or update Manga rating
         * @param {string} mangaId 
         * @param {RatingMangaIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postRatingMangaId: async (mangaId: string, body?: RatingMangaIdBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mangaId' is not null or undefined
            if (mangaId === null || mangaId === undefined) {
                throw new RequiredError('mangaId','Required parameter mangaId was null or undefined when calling postRatingMangaId.');
            }
            const localVarPath = `/rating/{mangaId}`
                .replace(`{${"mangaId"}}`, encodeURIComponent(String(mangaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RatingApi - functional programming interface
 * @export
 */
export const RatingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Manga rating
         * @param {string} mangaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRatingMangaId(mangaId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await RatingApiAxiosParamCreator(configuration).deleteRatingMangaId(mangaId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get your ratings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRating(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20013>>> {
            const localVarAxiosArgs = await RatingApiAxiosParamCreator(configuration).getRating(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create or update Manga rating
         * @param {string} mangaId 
         * @param {RatingMangaIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postRatingMangaId(mangaId: string, body?: RatingMangaIdBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await RatingApiAxiosParamCreator(configuration).postRatingMangaId(mangaId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RatingApi - factory interface
 * @export
 */
export const RatingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Delete Manga rating
         * @param {string} mangaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRatingMangaId(mangaId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return RatingApiFp(configuration).deleteRatingMangaId(mangaId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get your ratings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRating(options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20013>> {
            return RatingApiFp(configuration).getRating(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create or update Manga rating
         * @param {string} mangaId 
         * @param {RatingMangaIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postRatingMangaId(mangaId: string, body?: RatingMangaIdBody, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return RatingApiFp(configuration).postRatingMangaId(mangaId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RatingApi - object-oriented interface
 * @export
 * @class RatingApi
 * @extends {BaseAPI}
 */
export class RatingApi extends BaseAPI {
    /**
     * 
     * @summary Delete Manga rating
     * @param {string} mangaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RatingApi
     */
    public async deleteRatingMangaId(mangaId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return RatingApiFp(this.configuration).deleteRatingMangaId(mangaId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get your ratings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RatingApi
     */
    public async getRating(options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20013>> {
        return RatingApiFp(this.configuration).getRating(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create or update Manga rating
     * @param {string} mangaId 
     * @param {RatingMangaIdBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RatingApi
     */
    public async postRatingMangaId(mangaId: string, body?: RatingMangaIdBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return RatingApiFp(this.configuration).postRatingMangaId(mangaId, body, options).then((request) => request(this.axios, this.basePath));
    }
}
