/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * OpenAPI spec version: 5.10.0
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { InlineResponse20011 } from '../models';
import { ReferenceExpansionReport } from '../models';
import { ReportBody } from '../models';
import { ReportListResponse } from '../models';
import { Response } from '../models';
/**
 * ReportApi - axios parameter creator
 * @export
 */
export const ReportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of report reasons
         * @param {string} category 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReportReasonsByCategory: async (category: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            if (category === null || category === undefined) {
                throw new RequiredError('category','Required parameter category was null or undefined when calling getReportReasonsByCategory.');
            }
            const localVarPath = `/report/reasons/{category}`
                .replace(`{${"category"}}`, encodeURIComponent(String(category)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of reports by the user
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [category] 
         * @param {string} [reasonId] 
         * @param {string} [objectId] 
         * @param {string} [status] 
         * @param {string} [orderCreatedAt] 
         * @param {ReferenceExpansionReport} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports: async (limit?: number, offset?: number, category?: string, reasonId?: string, objectId?: string, status?: string, orderCreatedAt?: string, includes?: ReferenceExpansionReport, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/report`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (reasonId !== undefined) {
                localVarQueryParameter['reasonId'] = reasonId;
            }

            if (objectId !== undefined) {
                localVarQueryParameter['objectId'] = objectId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (orderCreatedAt !== undefined) {
                localVarQueryParameter['order[createdAt]'] = orderCreatedAt;
            }

            if (includes !== undefined) {
                localVarQueryParameter['includes[]'] = includes;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new Report
         * @param {string} contentType 
         * @param {ReportBody} [body] The size of the body is limited to 8KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postReport: async (contentType: string, body?: ReportBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling postReport.');
            }
            const localVarPath = `/report`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReportApi - functional programming interface
 * @export
 */
export const ReportApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of report reasons
         * @param {string} category 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReportReasonsByCategory(category: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20011>>> {
            const localVarAxiosArgs = await ReportApiAxiosParamCreator(configuration).getReportReasonsByCategory(category, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a list of reports by the user
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [category] 
         * @param {string} [reasonId] 
         * @param {string} [objectId] 
         * @param {string} [status] 
         * @param {string} [orderCreatedAt] 
         * @param {ReferenceExpansionReport} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReports(limit?: number, offset?: number, category?: string, reasonId?: string, objectId?: string, status?: string, orderCreatedAt?: string, includes?: ReferenceExpansionReport, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ReportListResponse>>> {
            const localVarAxiosArgs = await ReportApiAxiosParamCreator(configuration).getReports(limit, offset, category, reasonId, objectId, status, orderCreatedAt, includes, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a new Report
         * @param {string} contentType 
         * @param {ReportBody} [body] The size of the body is limited to 8KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postReport(contentType: string, body?: ReportBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Response>>> {
            const localVarAxiosArgs = await ReportApiAxiosParamCreator(configuration).postReport(contentType, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ReportApi - factory interface
 * @export
 */
export const ReportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get a list of report reasons
         * @param {string} category 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReportReasonsByCategory(category: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20011>> {
            return ReportApiFp(configuration).getReportReasonsByCategory(category, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of reports by the user
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [category] 
         * @param {string} [reasonId] 
         * @param {string} [objectId] 
         * @param {string} [status] 
         * @param {string} [orderCreatedAt] 
         * @param {ReferenceExpansionReport} [includes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReports(limit?: number, offset?: number, category?: string, reasonId?: string, objectId?: string, status?: string, orderCreatedAt?: string, includes?: ReferenceExpansionReport, options?: AxiosRequestConfig): Promise<AxiosResponse<ReportListResponse>> {
            return ReportApiFp(configuration).getReports(limit, offset, category, reasonId, objectId, status, orderCreatedAt, includes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new Report
         * @param {string} contentType 
         * @param {ReportBody} [body] The size of the body is limited to 8KB.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postReport(contentType: string, body?: ReportBody, options?: AxiosRequestConfig): Promise<AxiosResponse<Response>> {
            return ReportApiFp(configuration).postReport(contentType, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReportApi - object-oriented interface
 * @export
 * @class ReportApi
 * @extends {BaseAPI}
 */
export class ReportApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of report reasons
     * @param {string} category 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public async getReportReasonsByCategory(category: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20011>> {
        return ReportApiFp(this.configuration).getReportReasonsByCategory(category, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a list of reports by the user
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [category] 
     * @param {string} [reasonId] 
     * @param {string} [objectId] 
     * @param {string} [status] 
     * @param {string} [orderCreatedAt] 
     * @param {ReferenceExpansionReport} [includes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public async getReports(limit?: number, offset?: number, category?: string, reasonId?: string, objectId?: string, status?: string, orderCreatedAt?: string, includes?: ReferenceExpansionReport, options?: AxiosRequestConfig) : Promise<AxiosResponse<ReportListResponse>> {
        return ReportApiFp(this.configuration).getReports(limit, offset, category, reasonId, objectId, status, orderCreatedAt, includes, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a new Report
     * @param {string} contentType 
     * @param {ReportBody} [body] The size of the body is limited to 8KB.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public async postReport(contentType: string, body?: ReportBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<Response>> {
        return ReportApiFp(this.configuration).postReport(contentType, body, options).then((request) => request(this.axios, this.basePath));
    }
}
