/* tslint:disable */
/* eslint-disable */
/**
 * MangaDex API
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * OpenAPI spec version: 5.10.0
 * Contact: support@mangadex.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface ApiClientAttributes
 */
export interface ApiClientAttributes {

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    name?: string;

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    profile?: string;

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    clientId?: string | null;

    /**
     * @type {number}
     * @memberof ApiClientAttributes
     */
    version?: number;

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    createdAt?: string;

    /**
     * @type {string}
     * @memberof ApiClientAttributes
     */
    updatedAt?: string;
}
